export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const UPDATE_QUANTITY_CART_ITEM = "UPDATE_QUANTITY_CART_ITEM";
export const ADD_ORDER = "ADD_ORDER";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
